name: Java CI

on:
  push:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: nelonoel/branch-name@v1.0.1

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 0.1.${{ github.run_number }}
          release_name: Release 0.1.${{ github.run_number }}
          draft: false
          prerelease: false

